# Site settings 
title: Bliss Colour and Design
description: The most trusted colour expert in the South-West.

baseurl: ""
url: "https://blisscolouranddesign.com.au"

# Jekyll version 
version: "3.8.4" 

# Banner-tagline
banner-tagline: The most trusted colour expert in the South-West.

relative_permalinks: false

github_username: darcemac
name: Darcy McDonald

locale: en-AU

# Build settings
markdown: kramdown

permalink: /projects/:title/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  endings: all
  ignore:
    envs: [local]

exclude: ["node_modules", "gulpfile.js", "package.json"]

