# Site settings
title: Bliss Colour & Design 
email: meagan@blisscolouranddesign.com.au
phone: 0438 409 407
phone-clean: 0438409407
insta: "https://www.instagram.com/blisscolouranddesign"
facebook: "https://www.facebook.com/blisscolouranddesign"
  
description: > # this means to ignore newlines until "baseurl:"
  The most trusted colour expert in the South-West.

baseurl: ""
url: "https://blisscolouranddesign.com.au"

# Jekyll version 
version: "3.8.4" 

# CloudCannon defaults
uploads_dir: "images/uploads"

# Banner-tagline
banner-tagline: The most trusted colour expert in the South-West.

relative_permalinks: false

github_username: darcemac
name: Darcy McDonald

locale: en-AU

# Build settings
markdown: kramdown

permalink: /projects/:title/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  endings: all
  ignore:
    envs: [local]

exclude: ["node_modules", "gulpfile.js", "package.json"]

